jmonkey:
  log:
    save: false #是否存储日志
    debug: false #是否打印访问接口日志
  redis:
    host: localhost
    port: 6379
    database: 10
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ieg?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
  static-locations-path: http://192.168.1.8:8080/assets/
  static-locations-file: E:/JMonkeyFile
  filePath: /assets
  fileTempMemory: E:/fileTempMemory
  thymeleaf:
    staticPath: http://localhost:8080/lib/ #https://cdn.bootcss.com/
  user:
    photo: ${jmonkey.filePath}/user/photo/
  ieg:
    file-test: 艾 特 诗 教 育
    file-font: 20
    school:
      img:
        logo: ${jmonkey.filePath}/ieg/school/logo/
        describe: ${jmonkey.filePath}/ieg/school/describe/
        faculty: ${jmonkey.filePath}/ieg/school/faculty/
        life: ${jmonkey.filePath}/ieg/school/life/
        scholarship: ${jmonkey.filePath}/ieg/school/scholarship/
      faculty: ${jmonkey.filePath}/ieg/faculty/
      problem: ${jmonkey.filePath}/ieg/school/problem/
      enroll: ${jmonkey.filePath}/ieg/school/enroll/
      major: ${jmonkey.filePath}/ieg/school/major/
      major-problem: ${jmonkey.filePath}/ieg/school/major/problem/
      environment: ${jmonkey.filePath}/ieg/environment/
    enroll: ${jmonkey.filePath}/ieg/enroll/
    grade: ${jmonkey.filePath}/ieg/school/grade/
  gauge:
    icon-path:${jmonkey.filePath}/gauge/
